services:
  - type: web
    name: form-submission-api
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASS
        sync: false
      - key: API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
